package com.todomanagement.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Schema(description = "Data Transfer Object for Todo items")
public class TodoDto {

    @Schema(description = "Unique identifier of the Todo item, automatically generated by the system", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Title of the Todo item", example = "Buy groceries")
    private String title;

    @Schema(description = "Description of the Todo item", example = "Milk, Eggs, Bread")
    private String description;

    @Schema(description = "Completion status of the Todo item", example = "false")
    private boolean completed;
}
